### ISSUE TITLE
Preserve local state is not working (name misspelling)

### ISSUE THREAD

**Issue by asv1** [svitejs/svite#11]
## Description

Setting [preserveState](https://github.com/svitejs/svite/blob/3a9e1a069450cd3fa009716192dc645802e5370e/packages/vite-plugin-svelte/src/utils/options.ts#L195) to true is not working because svelte-hmr uses [preserveLocalState](https://github.com/rixo/svelte-hmr#preservelocalstate).

**Comment by dominikg** [comment]
updated in 0.11.1, thanks.

Please only change the svelte-hmr options if you know what you're getting into, they are there for advanced usecases and tool integrations, i don't expect projects built with vite-plugin-svelte to use them.
