### ISSUE TITLE
Error: Function called outside component initialization when calling `setContext`

### ISSUE THREAD

**Issue by ebeloded** [svitejs/svite#12]
## Description

`setContext` throws an error `Error: Function called outside component initialization`

## Reproduction

1. Initialize svite app (with any template)

2. Add the following lines to App.svelte
```ts
import { setContext } from 'svelte';
setContext({},{})
```

## Additional Information

- operating system Mac OS
- versions for
  - "vite": "2.0.5",
  - "svelte": "3.35.0",
  - "@svitejs/vite-plugin-svelte": "0.11.0",

Update:

Same is true for any component initialization function. For example, the following will generate same error:
```ts
import { createEventDispatcher } from 'svelte'
const dispatch = createEventDispatcher()
```

**Comment by dominikg** [comment]
I can not reproduce the issue on linux. I'll try to add more tests, they are run on mac aswell. But please try again with latest versions, there have been sevaral important fixes in vite 2.1

```sh
npx svite create
cd svite-minimal
npm install
# edit App.svelte
npm run dev  #devserver starts, page opens, no errors
# edit App.svelte again to test hmr, still no errors, hmr works
```

dependency versions used:
```
@svitejs/vite-plugin-svelte 0.11.1
svelte 3.35.0
svelte-hmr 0.13.3
vite 2.1.2
```

**Comment by ebeloded** [comment]
I tried again, yet still getting the same error. Here is the repo: https://github.com/ebeloded/svite-issue-12

Here is what I'm seeing:
![image](https://user-images.githubusercontent.com/5859177/111849762-f9fdbc80-8940-11eb-81ef-b21581550477.png)

**Comment by ebeloded** [comment]
I just dockerized the app to see if the issue is related to the OS, and I can confirm - it runs fine in Docker container, but fails outside of it.

**Comment by ebeloded** [comment]
@dominikg I found out that this happens when the path to the app folder contains a space character.

**Comment by dominikg** [comment]
Sorry for not getting back to this sooner. This is an upstream issue: https://github.com/vitejs/vite/pull/2614

**Comment by dominikg** [comment]
upstream has been fixed, should work with latest vite

**Comment by ebeloded** [comment]
Great. Thanks for the update!
