### ISSUE TITLE
The CSS in the compiler options option does not work in the production environment

### ISSUE THREAD

**Issue by ranchoX** [svitejs/svite#13]
## Description

//vite.config.js file

```
export default defineConfig({
  plugins: [svelte({
    compilerOptions:{
      css:true,
    },
  })],
})
```
In the production not work.
![image](https://user-images.githubusercontent.com/2391528/111767657-eff8a100-88e1-11eb-911f-b72218258f80.png)

I think the following line of code has an impact

https://github.com/svitejs/svite/blob/1ddc78417259d70aa7cdff49b4eaebf7d5434df8/packages/vite-plugin-svelte/src/utils/compile.ts#L32

**Comment by ranchoX** [comment]
I'll make it easier to load svelte components without having to load two files

**Comment by dominikg** [comment]
Easier to load really depends on the usecase. But it looks like i was wrong to assume emit would fit everyone. A future version of vite-plugin-svelte is going to support emitCss: false for production builds. see linked issue above
