### ISSUE TITLE
CSS keyframes are lost on build

### ISSUE THREAD

**Issue by gottlike** [svitejs/svite#16]
When CSS animations are used in a Svelte file, the production CSS doesn't include them. E. g.:

```html
<style>
  .spinner {
    border-top-color: #aaaaaa;
    -webkit-animation: spinner 0.5s linear infinite, delayed_fade_in 0.5s;
            animation: spinner 0.5s linear infinite, delayed_fade_in 0.5s;
  } @-webkit-keyframes spinner {
    0%   { -webkit-transform: rotate(0deg); }
    100% { -webkit-transform: rotate(360deg); }
  } @keyframes spinner {
    0%   { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  } @-webkit-keyframes delayed_fade_in {
    0%   { opacity: 0; }
    33%  { opacity: 0; }
    100% { opacity: 1; }
  } @keyframes delayed_fade_in {
    0%   { opacity: 0; }
    33%  { opacity: 0; }
    100% { opacity: 1; }
  }
</style>
```

I'm using the `svite-postcss-tailwind` template from this project's playground: https://github.com/svitejs/svite/tree/main/packages/playground/svite-postcss-tailwind

**Comment by dominikg** [comment]
not entirely sure what's happening but please try to use a more up to date template. i'd recommend using vite-plugin-windicss instead of tailwind via postcss.

the templates and playground projects in this repo are out of date

**Comment by gottlike** [comment]
Just FYI, this part in the Tailwind config caused the keyframes to be purged (why is there even such an option.. ?)

```js
purge: {
  (...),
  options: {
    (...),
    keyframes: false
  }
}
```

I'll be using Windi CSS going forward - thanks for the suggestion 👍
