### ISSUE TITLE
Getting Started documentation in the README

### ISSUE THREAD

**Issue by imsys** [svitejs/svite#37]
I first found about Svite on github, and I was a little bit lost on how to use it. Then I found that the documentation was on [the npmjs page](https://www.npmjs.com/package/svite), so I would suggest to have that Getting Started and CLI usage copied over to the README file, so newcomers can easily find it on github too.

Thanks. ;)

**Comment by dominikg** [comment]
added links to readme.

fyi, the templates have been created a while ago and may no longer be state of the art. If they work for you, great, but please research current guides of involved projects too
