### ISSUE TITLE
I can't Get Any Of The Templates To Work

### ISSUE THREAD

**Issue by stevesob** [svitejs/svite#5]
## Templates Not Working

After cloning minimal template and running NPM INSTALL I get the following errors:
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

## Additional Information

If I'm doing something wrong a little extra documentation would help.
Thanks for working on this. I love the minimal approach!

- operating system
- versions for
  - node
  - 14.5.0
  - npm
  - 6.14.8
  - svite
  - 0.8.1
  - vite
  - 2.05.0
  - svelte
  - 3.35.0
- logs with debug enabled
  - start svite with `svite --debug` flag

**Comment by dominikg** [comment]
the templates are not meant to be cloned directly, the command you're looking for is `npx svite@beta create --t <template> `

you can also manually replace the workspace: ref in package.json with `^0.10.0` and it should work

**Comment by stevesob** [comment]
That worked! Thanks so much, I'm always amazed how much you guys know.

HMR doesn't appear to work. I added a simple counter tp app.svelte, and if I make a code change and save the counter gets reset to 0.

<script>
let counter=0
</script>

<button on:click={()=>counter++}>Counter: {counter}</button>

**Comment by dominikg** [comment]
hmr works unless you are seeing full page reloads.
preserving local state is off by default for consistency reasons. you can turn it on with `{hot:{ preserveLocalState: true}}` in plugin options. 

this is a work in progress, once its more complete and docs exist it will be explained.

**Comment by stevesob** [comment]
Understood. Looking forward to updates...

**Comment by dominikg** [comment]
closing here,  svite@0.8 has now been marked as deprecated and docs do explain how to use create cli
