### ISSUE TITLE
Unrecognized option 'cssHash'

### ISSUE THREAD

**Issue by henriquehbr** [svitejs/svite#7]
## Description

I'm trying to setup a simple Svelte app + TypeScript + Vite, when i try to run `vite` through the script `example:dev`, i get this error

**package.json**

```json
{
	"name": "example",
	"version": "1.0.0",
	"main": "src/index.js",
	"license": "MIT",
	"scripts": {
		"dev": "vite",
		"build": "vite build",
		"start": "sirv public -s"
	},
	"devDependencies": {
		"@svitejs/vite-plugin-svelte": "^0.10.0",
		"@tsconfig/svelte": "^1.0.10",
		"esbuild": "^0.8.29",
		"esbuild-svelte": "^0.4.0",
		"rimraf": "^3.0.2",
		"sirv-cli": "^1.0.10",
		"slash": "^3.0.0",
		"svelte": "^3.31.1",
		"svelte-check": "^1.1.26",
		"svelte-preprocess": "^4.6.1",
		"vite": "^2.0.5"
	},
	"dependencies": {
		"svelte-loadable": "^1.5.1",
		"svelte-routing": "^1.5.0"
	}
}
```

**vite.config.js**

```js
import path from 'path'

import { defineConfig } from 'vite'
import svelte from '@svitejs/vite-plugin-svelte'

export default defineConfig(({ mode }) => {
	const isProduction = mode === 'production'
	return {
		build: {
			polyfillDynamicImport: false,
			cssCodeSplit: false,
			minify: isProduction
		},
		extensions: ['html', 'js', 'css'],
		resolve: {
			alias: {
				svelte: path.resolve(__dirname, 'node_modules/svelte')
			}
		},
		plugins: [
			svelte({
				hot: !isProduction,
				emitCss: true
			})
			//indexReplace()
		],
		build: {
			minify: isProduction
		}
	}
})
```

## Reproduction

https://github.com/henriquehbr/svelte-typewriter/tree/repro/svite

## Additional Information

- Windows 10 (64-bit)
- node v15.11.0
- npm 7.6.0
- svite 0.10.0
- vite 2.0.5
- svelte 3.31.1

**Comment by henriquehbr** [comment]
Solved it! in the end, in the end it was a silly detail, i was reading [Svelte blog](https://svelte.dev/blog/whats-new-in-svelte-march-2021) searching for recent changes (as my version was slightly outdated) and turns out that `cssHash` is a new option released on `3.34.0`, and that explains such error, updating it solved it for me

Hope it might help someone in the future :)

**Comment by dominikg** [comment]
Hi, thanks for checking out @svitejs/vite-plugin-svelte.

some questions:
1) @svitejs/vite-plugin-svelte declares svelte ^3.35.0 as peer dependency, did you not get a warning about that?
2) your vite config has a duplicate build property, how does that work?
3) why do you alias 'svelte'
4) whats the purpose of the extensions on vite config? I only know about https://vitejs.dev/config/#resolve-extensions

**Comment by henriquehbr** [comment]
Hi there @dominikg

1. At first, i didn't noticed, but now you mentioned that, i tried reinstalling svite and, i got the following warning during the installation process: `warning "@svitejs/vite-plugin-svelte@0.10.0" has incorrect peer dependency "svelte@^3.35.0".`
2. It was a typo that i solved right after fixing this `cssHash` issue, i'm not sure, but iirc, the second one would overwrite the first
3. I'm not sure if that's still needed, i got introduced into Svelte + Vite by [svelte-routify-windi-vite](https://github.com/reepolee/svelte-routify-windi-vite), at least that's how things would work on a Rollup setup, about the reason for that, correct me if i'm wrong, but i think is due to a known behavior in how `svelte/internals` are fragmented, in the sense that each component has it's own, so in order to avoid having duplicated copies of the same package, `svelte` should be aliased to always point to the same package
4. Misinformation of mine, `.js` isn't really needed as it's included by default, about `.html` and `.css`, i don't really know why i've put them there, i think i've got to read more the docs 😬 

One suggestion that i think would be a good addition to the documentation, is having a "From scratch" section on how to include Vite in already existing projects, the CLI is cool and all, but it's not suitable for all use cases, the step-by-step guide is kinda scattered and implicit across the docs, even though the implementation process is kinda simple, it would be really handy to have a place to find information about migrating to Vite in a on-going project scenario
